SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE 
 FROM REST_INFO JOIN REST_REVIEW A USING (REST_ID) 
 WHERE ADDRESS LIKE '서울%'
 GROUP BY REST_ID
 ORDER BY SCORE DESC, FAVORITES DESC;